apiVersion: v1
kind: Secret
metadata:
  name: khazane-secrets
  namespace: khazane
type: Opaque
stringData:
  POSTGRES_USER: khazane
  POSTGRES_PASSWORD: khazane_secret_k8s
  POSTGRES_DB: khazane_db
  DATABASE_URL: postgresql://khazane:khazane_secret_k8s@postgres:5432/khazane_db
  JWT_SECRET: khazane-jwt-secret-production-k8s-2026
  REDIS_HOST: redis
